version: '3.9'

services:

  db:
    image: mysql:8.0.32
    container_name: curso-spring-aws-database
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: curso_udemy_spring_boot_aws
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - network

  api:
    image: tideeh/curso-udemy-spring-boot-aws
    container_name: curso-spring-aws-api
    pull_policy: always
    restart: always
    build: ./
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/curso_udemy_spring_boot_aws?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    name: curso-spring-aws-network
    driver: bridge