name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Hub Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      run: mvn clean install

    - name: Build Docker Compose
      run: docker-compose build
      
    - name: Push to Docker Hub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/curso-udemy-spring-boot-aws:latest ${{ secrets.DOCKER_USERNAME }}/curso-udemy-spring-boot-aws:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/curso-udemy-spring-boot-aws:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/curso-udemy-spring-boot-aws:latest
